#!/usr/bin/env ruby

require_relative "repl.rb"

if ARGV.delete("-l")
  # [Num] prints as 1\n2\n3 (default from file)
  $line_mode = true
end
if ARGV.delete("-L")
  # [Num] prints as 1 2 3 (default in repl)
  $line_mode = false
end

repl
