#!/usr/bin/env ruby

require_relative "repl.rb"

# only intended for docs test to print things like it was in repl
if ARGV.delete("-repl_mode")
  $repl_mode = true
elsif ARGV.delete("-no_repl_mode")
  $repl_mode = false
end

# Encoding.default_external="ASCII-8BIT"

repl
