allFiles = Dir['docs/*.md']
basenames = allFiles.map{|f| f.sub(/\.md$/,'').sub('docs/','') }

Navbar='<div id="navbar"><ul>
   <li id="atlas"><a href="index.html">Atlas</a></li><li>'+
   basenames.map{|n|
     "<a href=\"#{n}.html\">#{n.split('_').map{|word|word[0].upcase+word[1..-1]}*" "}</a>"
   }*" | "+
   '</li><li><a href="quickref.html">Quick Ref</a></li><li><a href="https://github.com/darrenks/atlas">Source</a></li>
</ul></div>'

def convertMd(filename)
   basefile = filename.sub(/\.md$/,'').sub('docs/','')
   basefile = "index" if basefile == "README"
   md = File.read(filename)

   # remove github readme warning
   md = md.lines.to_a[4..-1].join("\n") if basefile == "index"

   File.open('t.md','w'){|f|f<<md}
   markdown = `markdown.pl < t.md`
   `rm t.md`

   # pre shows up too small on mobile...
   markdown.gsub!("<pre>",'<div class="prog">')
   markdown.gsub!("</pre>",'</div>')

   title = markdown[/<h1>(.*?)<\/h1>/,1]

   markdown.gsub!(/<(h[1-3])>(.*?)<\/\1>/){"<#$1 id=\"#{$2.downcase.tr'^a-z0-9',''}\">#$2</#$1>"}

   if title.nil?
      puts 'skipping '+filename
      return
   end
   File.open('web/site/'+basefile+'.html','w'){|f|f<<'<!DOCTYPE HTML>
<html lang="en"><!-- This file is automatically generated from generate_site.rb by reading '+filename+' --><head><meta charset="utf-8"><title>'+title+'</title><link rel="stylesheet" href="style.css"><link rel="icon" type="image/x-icon" href="favicon.ico" /></head><body>'+Navbar+'<div id="content">'+markdown+'</div></body></html>'}
end

(allFiles<<"README.md").each{|f|
   convertMd(f)
}