require "./repl.rb"
require 'cgi'

class String
  def td
    "<td>"+self.escape+"</td>"
  end
  def escape
    CGI.escape_html self
  end
  def ref
    puts '<td colspan="4" class="center"><b>'+self+'</b></td>'
  end
end

class Op
  def ref
    puts "<tr class=\"code\">"
    puts name.td
    puts (sym||"").td
    if type_summary
      puts type_summary.gsub('->','→').gsub('[Char]','Str').td
    else
      if type.size==1
        type.each{|t|
          puts t.inspect.gsub('->','→').gsub('[Char]','Str').td
        }
      else
        print "<td>"
        puts type[0].inspect.gsub('->','→').gsub('[Char]','Str').escape
        type[1..-1].each{|t|
#           puts "<br>"
          puts t.inspect.gsub('->','→').gsub('[Char]','Str').escape
        }
        puts "</td>"
      end
    end
    examples.each{|example|
      puts example.gsub('->','→').td
    }
#     puts "no_zip=true" if no_zip
    puts "</tr>"
  end
end

puts '<!DOCTYPE HTML >
<html><!-- This file is automatically generated from quickref.rb by reading ops.rb --><head><meta charset="utf-8" /><title>Atlas Quick Ref</title><link rel="stylesheet" href="quickref.css"><link rel="icon" href="favicon.ico"></head><body><table>
<tr><th>Name</th><th>Sym</th><th>Type</th><th>Example</th></tr>'

OpsList.reject{|o| !(String===o) && o.name =~ /^implicit/ }.each{|o|
  o.ref
}

puts '</table></body></html>'